name: Build-Docker

on: [push]

env:
  IMAGE_NAME: galactros/integration-project-webapp

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout SCM
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Docker build and push
      run: |
        docker build . -t ${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.IMAGE_NAME }}:latest
